{
    "system_active": true,
    "error_reporting": false,
    "website_template": "${WEBSITE_TEMPLATE}",
    "maintenance_page": "https://webenginecms.org/",
    "admins": {
        "${WEBENGINE_ADMIN_USER}": 100
    },
    "server_name": "${SERVER_NAME}",
    "website_title": "${WEBSITE_TITLE}",
    "website_meta_description": "MU Online Season 6 private server.",
    "website_meta_keywords": "MU, MU Online, Season 6, private server",
    "website_forum_link": "https://webenginecms.org/",
    "SQL_DB_HOST": "${DB_HOST}",
    "SQL_DB_NAME": "${DB_NAME}",
    "SQL_DB_2_NAME": "${DB_NAME}",
    "SQL_DB_USER": "${DB_USER}",
    "SQL_DB_PASS": "${DB_PASS}",
    "SQL_DB_PORT": "${DB_PORT}",
    "SQL_USE_2_DB": false,
    "SQL_PDO_DRIVER": "${SQL_PDO_DRIVER}",
    "SQL_PASSWORD_ENCRYPTION": "none",
    "SQL_SHA256_SALT": "1234567890",
    "server_files": "igcn",
    "language_switch_active": true,
    "language_default": "en",
    "language_debug": false,
    "plugins_system_enable": true,
    "ip_block_system_enable": false,
    "character_avatars_dir": "character-avatars",
    "player_profiles": true,
    "guild_profiles": true,
    "username_min_len": 4,
    "username_max_len": 10,
    "password_min_len": 4,
    "password_max_len": 20,
    "webengine_cms_installed": true,
    "cron_api": true,
    "cron_api_key": "123456",
    "social_link_facebook": "https://facebook.com/",
    "social_link_instagram": "https://instagram.com/",
    "social_link_discord": "https://discord.com/",
    "server_info_season": "Season 6",
    "server_info_exp": "500x",
    "server_info_masterexp": "250x",
    "server_info_drop": "50%",
    "maximum_online": "500",
    "season_1_support": false,
    "allow_duplicate_emails": false
}
